// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator for NON-COMMERCIAL USE
// Generator: RgenTemplate (internal)
// Generation date: 2014-06-02 01:10
// Generated by: GTS-DEV\Pranolo
//-------------------------------------------------------
namespace NotifyPropertyChangedRgen
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.6.0")]
    [Kodeo.Reegenerator.Generators.TemplateDisplayAttribute(DisplayName="NotifyPropertyChanged", Description="NotifyPropertyChanged", HideInDialog=false)]
    public partial class NotifyPropertyChanged : CodeRendererEx
    {
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<param name="className"></param>
        ///<param name="IncludeNPC"></param>
        public virtual void OutFunctions(String className, Boolean IncludeNPC)
        {
            this.Output.Write("\t");
 if (IncludeNPC) { 
            this.Output.Write(" \r\n\t\tpublic event System.ComponentModel.PropertyChangedEventHandler PropertyChang" +
                    "ed;\r\n\t");
} 
            this.Output.Write("\r\n\r\n    void ");
            this.Output.Write( INotifierFullName );
            this.Output.Write(".Notify(string propertyName) {  \r\n\t\tif (PropertyChanged != null) {\r\n            P" +
                    "ropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(property" +
                    "Name));\r\n        }\r\n    }");
            this.Output.WriteLine();
        }
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        public virtual void Test()
        {
            this.Output.WriteLine();
        }
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<param name="tag"></param>
        ///<param name="propName"></param>
        ///<param name="propType"></param>
        ///<param name="existingComment"></param>
        ///<param name="attributes"></param>
        ///<param name="interfaceImpl"></param>
        public virtual void OutProperty(String tag, String propName, String propType, String existingComment, String attributes, String interfaceImpl)
        {
            this.Output.Write("\t#region ");
            this.Output.Write( tag);
            this.Output.Write("\r\n    private ");
            this.Output.Write( propType );
            this.Output.Write(" _");
            this.Output.Write( propName );
            this.Output.Write("; \r\n\t");
            this.Output.Write( existingComment );
            this.Output.Write("\r\n\t");
            this.Output.Write( attributes 	);
            this.Output.Write("\r\n\tpublic ");
            this.Output.Write( propType );
            this.Output.Write(" ");
            this.Output.Write( propName );
            this.Output.Write(" {\r\n        get {\r\n            return _");
            this.Output.Write( propName );
            this.Output.Write(";\r\n        }\r\n        set {\r\n            ");
 //Left empty to be filled by Generated code
            this.Output.Write("\r\n        }\r\n    }\r\n\t#endregion");
            this.Output.WriteLine();
        }
    }
}
